--- # Nofifications and handlers demo

- hosts: centos
  remote_user: ansible
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: yes
  tasks:
    - name: Install NGINX
      yum:
        name: nginx
        state: latest
      register: yum_result
      notify:
        - Enable and start NGINX service
    - debug: var=yum_result
  handlers:
    - name: Enable and start NGINX service
      service: 
        name: nginx
        enabled: yes
        state: restarted
          
